version: 2.1
orbs:
  node: circleci/node@1.1
  heroku: circleci/heroku@1.2.6
jobs:
  run_tests:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd backend && npm install
      - run: cd backend && npm run test
  deploy_frontend:
    executor:
      name: node/default
    steps:
        - run:
            command: |
              echo ls
              cd backend
              cd frontend
              npm install
              npx expo login --non-interactive -u zhu.kerry1@gmail.com
              npx expo publish --non-interactive

workflows:
  heroku_deploy:
    jobs:
      # - run_tests
      # - heroku/deploy-via-git:
      #     branch: production
      #     force: true
      #     filters:
      #         branches:
      #           only:
      #             - production
      - deploy_frontend
